# Generated by Django 4.1.1 on 2022-09-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
