# Generated by Django 4.1.1 on 2022-09-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraudapp', '0002_alter_persondata_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatcherRulesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.TextField()),
                ('rule_tag', models.CharField(max_length=50)),
                ('rule_description', models.TextField()),
                ('rule_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonDataMatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('match_status', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
