# Generated by Django 4.1.1 on 2022-09-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('GENERIC', 'Generic'), ('ALLOWED_USER', 'AllowedUser')], max_length=100),
        ),
    ]
